from src.board import Board, SquareState
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from src.game import MinesweeperGame


class MinesweeperSolver:
    def __init__(self, game: Any):
        self.game = game
        self.board: Board = game.board

    def solve_board(self):
        """
        Solve the Minesweeper game using deterministic logic.

        The solver repeatedly:
        1. Applies simple local Minesweeper rules.
        2. Applies subset/set-difference logic.

        If neither technique can make further progress, the solver stops.
        """
        while not self.board.check_win() and not self.board.check_lose():
            progress_made = False

            # Step 1: Apply simple local rules.
            for y in range(self.board.num_rows):
                for x in range(self.board.num_cols):
                    if self.board.get_square_state(x, y) != SquareState.REVEALED:
                        continue

                    if self.simple_resolve_surrounding(x, y):
                        progress_made = True

            if self.board.check_win() or self.board.check_lose():
                break

            # Step 2: Apply subset/set-difference logic.
            if not progress_made:
                if self.apply_set_logic():
                    progress_made = True

            # No deterministic progress can be made.
            if not progress_made:
                break

    def simple_resolve_surrounding(self, x: int, y: int) -> bool:
        """
        Apply basic Minesweeper rules to a revealed square.

        Rule 1:
            If the number of surrounding flags equals the square's value,
            all remaining unrevealed surrounding squares are safe.

        Rule 2:
            If the number of unrevealed surrounding squares equals the
            number of mines still needed, all of those squares are mines.

        Returns:
            True if at least one square was revealed or flagged.
        """
        value = self.board.get_square_value(x, y)

        # This method should only be called on revealed squares, but avoid
        # treating a mine as a numbered square just in case.
        if value < 0:
            return False

        progress_made = False

        surrounding_squares = self.board.get_surrounding_squares(x, y)

        flagged = []
        unrevealed = []

        for square in surrounding_squares:
            state = self.board.get_square_state(square[0], square[1])

            if state == SquareState.FLAGGED:
                flagged.append(square)
            elif state == SquareState.UNREVEALED:
                unrevealed.append(square)

        num_flags = len(flagged)
        mines_needed = value - num_flags

        # Rule 1:
        # We have already identified every mine surrounding this square,
        # so every remaining unrevealed square is safe.
        if mines_needed == 0:
            for square in unrevealed:
                self.game.reveal_square(square[0], square[1])
                progress_made = True

        # Rule 2:
        # Every unrevealed square must be a mine.
        elif mines_needed == len(unrevealed):
            for square in unrevealed:
                self.game.toggle_flag_square(square[0], square[1])
                progress_made = True

        return progress_made

    def apply_set_logic(self) -> bool:
        """
        Compare sets of unrevealed squares surrounding revealed cells.

        If Set A is a subset of Set B, then:

            B - A

        contains:

            mines(B) - mines(A)

        mines.

        Therefore:
            - If the difference requires 0 mines, every square in the
              difference is safe.
            - If the difference requires exactly len(difference) mines,
              every square in the difference is a mine.

        Returns:
            True if at least one square was revealed or flagged.
        """
        progress_made = False

        revealed_numbers = []

        # Build the constraints generated by each revealed numbered square.
        for y in range(self.board.num_rows):
            for x in range(self.board.num_cols):
                if self.board.get_square_state(x, y) != SquareState.REVEALED:
                    continue

                value = self.board.get_square_value(x, y)

                # Only numbered squares generate constraints.
                if value <= 0:
                    continue

                surrounding = self.board.get_surrounding_squares(x, y)

                unrevealed = {
                    square
                    for square in surrounding
                    if self.board.get_square_state(
                        square[0],
                        square[1]
                    ) == SquareState.UNREVEALED
                }

                flags = {
                    square
                    for square in surrounding
                    if self.board.get_square_state(
                        square[0],
                        square[1]
                    ) == SquareState.FLAGGED
                }

                mines_needed = value - len(flags)

                # An inconsistent constraint should never occur if all
                # flags are correct. Ignore it rather than making unsafe
                # deductions.
                if mines_needed < 0 or mines_needed > len(unrevealed):
                    continue

                revealed_numbers.append({
                    "pos": (x, y),
                    "set": unrevealed,
                    "needed": mines_needed,
                })

        # Compare every pair of constraints.
        for i in range(len(revealed_numbers)):
            for j in range(len(revealed_numbers)):
                if i == j:
                    continue

                a = revealed_numbers[i]
                b = revealed_numbers[j]

                set_a = a["set"]
                set_b = b["set"]

                # We can only subtract A from B if A is a subset of B.
                if not set_a.issubset(set_b):
                    continue

                diff_set = set_b - set_a
                diff_mines = b["needed"] - a["needed"]

                if not diff_set:
                    continue

                # Difference contains no mines.
                if diff_mines == 0:
                    for x, y in diff_set:
                        self.game.reveal_square(x, y)

                    progress_made = True

                # Every square in the difference is a mine.
                elif diff_mines == len(diff_set):
                    for x, y in diff_set:
                        self.game.toggle_flag_square(x, y)

                    progress_made = True

        return progress_made